set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
" set lines=25 columns=100         " Window dimensions.
set fuoptions=maxvert,maxhorz     " Set screen size to max

set guioptions-=r                 " Don't show right scrollbar

