colorscheme solarized
set guifont=Inconsolata:h14       " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set background=dark               " Background.
call togglebg#map("<F5>")         " Map <F5> to toggle light/dark background
" set lines=25 columns=100         " Window dimensions.
set fuoptions=maxvert,maxhorz     " Set screen size to max

set guioptions-=r                 " Don't show right scrollbar

