export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/mongodb/bin:/Users/d.mcclain/bin:$PATH"

# import git completion script
source ~/.git-completion.sh
GIT_PS1_SHOWDIRTYSTATE='true'
# format command prompt as current_dir (branch)
PS1='\W $(__git_ps1 "(%s) ")λ '

# Can't remember where this came from of if it's important
export DYLD_LIBRARY_PATH="/usr/local/mysql/lib:$DYLD_LIBRARY_PATH"

if [[ -s /Users/davidamcclain/.rvm/scripts/rvm ]] ; then source /Users/davidamcclain/.rvm/scripts/rvm ; fi

VIM_APP_DIR=/usr/bin/	

# ModCloth settings for managing memory with e-comm
export RUBY_GC_MALLOC_LIMIT="50000000"
export RUBY_HEAP_MIN_SLOTS="500000"
export RUBY_HEAP_SLOTS_GROWTH_FACTOR="1"
export RUBY_HEAP_SLOTS_INCREMENT="250000"

TERM="xterm"
export TERM

## after saving run
## source ~/.bashrc

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
